services:
  HomeQRinv:
    restart: unless-stopped
    image: python:3.12-slim
    working_dir: /home/app
    volumes:
      # Map your application directory from the host into the container
      - /app:/home/app
    command: >
      sh -c "
        pip install -r requirements.txt &&
        uvicorn app:app --host 0.0.0.0 --port 8443 --ssl-keyfile key.pem --ssl-certfile cert.pem
      "
    ports:
      - "8443:8443"
networks: {}